django_practice_verp/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
]

django_practice_verp/django_practice_verp/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView

urlpatterns = [
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/bbs/')),
]

django_practice_verp/bbs/models.py
from django.db import models

class Post(models.Model):
    content = models.CharField(max_length=200)
    user_name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.content

django_practice_verp/bbs/forms.py
from django import forms
from .models import Post

class SearchForm(forms.Form):
    keyword = forms.CharField(label='検索', max_length=100)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =('content', 'user_name')

django_practice_verp/bbs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post
from .forms import SearchForm, PostForm


# 一覧表示
def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        posts = Post.objects.filter(content__contains=keyword)
    else:
        searchForm = SearchForm()
        posts = Post.objects.all()
        
    context = {
        'message': 'Welcome to Practice BBS',
        'posts': posts,
        'searchForm': searchForm,
    }
    return render(request, 'bbs/index.html', context)

# 個別表示
def detail(request, id):
    post = get_object_or_404(Post, pk=id)

    context = {
        'message': 'Show Post ' + str(id),
        'post': post,        
    }
    return render(request, 'bbs/detail.html', context)

# 新規作成
def new(request):
    postForm = PostForm()

    context = {
        'message': 'New Post',
        'postForm': postForm,        
    }
    return render(request, 'bbs/new.html', context)

# 新規投稿
def create(request):
    if request.method == 'POST':
        postForm = PostForm(request.POST)
        if postForm.is_valid():
            post = postForm.save()

    context = {
        'message': 'Create post ' + str(post.id),
        'post': post,
    }
    return render(request, 'bbs/detail.html', context)

# 編集
def edit(request, id):
    post = get_object_or_404(Post, pk=id)
    postForm = PostForm(instance=post)

    context = {
        'message': 'Edit Post',
        'post': post,
        'postForm': postForm,        
    }
    return render(request, 'bbs/edit.html', context)

# 更新
def update(request, id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=id)
        postForm = PostForm(request.POST, instance=post)
        if postForm.is_valid():
            postForm.save()

    context = {
        'message': 'Update post ' + str(id),
        'post': post,
    }
    return render(request, 'bbs/detail.html', context)

# 削除
def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()

    posts = Post.objects.all()
    context = {
        'message': 'Delete Post ' + str(id),
        'posts': posts,        
    }
    return render(request, 'bbs/index.html', context)


# python manage.py runserver
# http://localhost:8000/
# python manage.py makemigrations
# python manage.py migrate

django_practice_verp/bbs/templates/bbs/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>Django練習用BBS</title>
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <style>body {padding: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "bbs:index" %}'>Django練習用BBS</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

django_practice_verp/bbs/templates/bbs/detail.html
{% extends './base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <h1>{{ message }}</h1>

    <p>{{ post.content }},{{ post.user_name }}</p>

    <div>
        <a href="{% url 'bbs:index' %}" class='btn btn-outline-primary'>一覧</a>
        <a href="{% url 'bbs:edit' post.id %}" class='btn btn-outline-primary'>編集</a>
        <a href="{% url 'bbs:delete' post.id %}" class='btn btn-outline-secondary'>削除</a>
    </div>
    
{% endblock %}

django_practice_verp/bbs/templates/bbs/edit.html
{% extends './base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  
    <h1>{{ message }}</h1>

    <form action='{% url "bbs:update" post.id %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form postForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>保存する</button>
        <a href="{% url 'bbs:detail' post.id %}" class="btn btn-outline-secondary">戻る</a>
    </form>

{% endblock %}

django_practice_verp/bbs/templates/bbs/index.html
{% extends './base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container-md mt-4">

    <h1>{{ message }}</h1>

    {% if searchForm %}
        <form action='{% url "bbs:index" %}' method='get'>
            <div class='d-flex gap-2 flex-wrap align-items-center mb-3'>
                {% bootstrap_form searchForm layout='inline' show_label=False %}
                <input type='submit' class="btn btn-outline-primary" value="OK" />
                <a href="{% url 'bbs:index' %}" class="btn btn-outline-secondary">クリア</a>
            </div>
        </form>
    {% endif %}

    <div class="table-responsive">
        <table class='table table-striped table-hover'>
            {% for post in posts %}
                <tr>
                    <td>{{ post.content }}</td>
                    <td>{{ post.user_name }}</td>
                    <td><a href="{% url 'bbs:detail' post.id %}" class='btn btn-outline-primary'>詳細</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

        <p>
            <a href="{% url 'bbs:new' %}" class='btn btn-outline-primary'>新規</a>
        </p>

</div>
{% endblock %}

django_practice_verp/bbs/templates/bbs/new.html
{% extends './base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  
    <h1>{{ message }}</h1>

    <form action='{% url "bbs:create" %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form postForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>作成する</button>
        <a href="{% url 'bbs:index' %}" class="btn btn-outline-secondary">戻る</a>
    </form>

{% endblock %}